name: ht_auth_client
description: Defines the abstract interface for authentication operations within the Headlines Toolkit, supporting email+code and anonymous flows.
repository: https://github.com/headlines-toolkit/ht-auth-client
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
